# Generated by Django 5.2 on 2025-04-24 08:58

import Usuario_App.models.estudiantes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario_App', '0002_alter_customuser_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudianteprofile',
            name='apellido_paterno',
        ),
        migrations.RemoveField(
            model_name='estudianteprofile',
            name='nombre',
        ),
        migrations.AddField(
            model_name='estudianteprofile',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('docente', 'Docente'), ('estudiante', 'Estudiante'), ('admin', 'Admin')], max_length=10),
        ),
        migrations.AlterField(
            model_name='estudianteprofile',
            name='edad',
            field=models.PositiveIntegerField(validators=[Usuario_App.models.estudiantes.validate_edad]),
        ),
    ]
