# Generated by Django 5.2 on 2025-04-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_password_alter_usuario_tipoderol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='idusuario',
            field=models.CharField(max_length=16),
        ),
    ]
