# Generated by Django 5.2 on 2025-04-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=100)),
                ('tema', models.CharField(max_length=100)),
                ('pregunta', models.TextField()),
                ('opa', models.CharField(max_length=255)),
                ('opb', models.CharField(max_length=255)),
                ('opc', models.CharField(max_length=255)),
                ('opcorrecta', models.CharField(max_length=50)),
            ],
        ),
    ]
