# Generated by Django 5.2 on 2025-04-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='opcorrecta',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='tema',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
