# Generated by Django 5.2 on 2025-05-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_App', '0002_alter_pregunta_opcorrecta_alter_pregunta_tema'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='opd',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
