# Generated by Django 5.2 on 2025-05-03 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_App', '0003_pregunta_opd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='opd',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
