# Generated by Django 5.2 on 2025-04-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario_App', '0003_remove_estudianteprofile_apellido_paterno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docenteprofile',
            name='apellido_materno',
        ),
        migrations.RemoveField(
            model_name='docenteprofile',
            name='apellido_paterno',
        ),
        migrations.RemoveField(
            model_name='docenteprofile',
            name='nombre',
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name2',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
