# Generated by Django 5.2 on 2025-04-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario_App', '0005_remove_estudianteprofile_apellido_materno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudianteprofile',
            name='carr_op_C',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
