# Generated by Django 5.2 on 2025-04-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario_App', '0006_estudianteprofile_carr_op_c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudianteprofile',
            name='carr_op_A',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='estudianteprofile',
            name='carr_op_B',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='estudianteprofile',
            name='carr_op_C',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
