# Generated by Django 5.2 on 2025-05-02 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario_App', '0007_alter_estudianteprofile_carr_op_a_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta_id', models.IntegerField()),
                ('respuesta', models.CharField(max_length=1)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario_App.estudianteprofile')),
            ],
        ),
    ]
