# Generated by Django 5.2 on 2025-05-03 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario_App', '0008_respuesta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Respuesta',
        ),
    ]
