# Generated by Django 5.2 on 2025-05-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario_App', '0009_delete_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudianteprofile',
            name='fecha_realizacion',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
