# Generated by Django 5.2 on 2025-06-01 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario_App', '0010_estudianteprofile_fecha_realizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=30)),
                ('correctas', models.PositiveIntegerField()),
                ('nota_parcial', models.FloatField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='Usuario_App.estudianteprofile')),
            ],
            options={
                'unique_together': {('estudiante', 'materia')},
            },
        ),
    ]
